name: Build IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask flutter
          flutter doctor

      - name: Install dependencies
        working-directory: ./app_web_view
        run: |
          flutter pub get
          cd ios
          pod install

      - name: Build iOS no-codesign
        working-directory: ./app_web_view
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        working-directory: ./app_web_view
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app_web_view.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app_web_view.ipa
          path: app_web_view/app_web_view.ipa
